name: recycling_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.5.4
dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    firebase_core: ^3.13.0
    yandex_mapkit: ^4.1.0
    cloud_firestore: ^5.6.6
    easy_localization: ^3.0.7+1
    flutter_svg: ^2.0.17
    flutter_bloc: ^8.0.1
    shimmer: ^3.0.0
    provider: ^6.1.4
    mobile_scanner: ^6.0.7
    flutter_styled_toast: any
    geolocator: any
    permission_handler: ^12.0.0+1
    get_it: ^8.0.3
    flutter_launcher_icons: ^0.14.3
    flutter_screenutil: ^5.9.3
    equatable: ^2.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^4.0.0

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/image/app_logo.png"
    min_sdk_android: 21

flutter:
    uses-material-design: true

    assets:
        - assets/icon/
        - assets/translations/
        - assets/fonts/
        - assets/image/

    fonts:
        - family: SeoulNamsan
          fonts:
              - asset: assets/fonts/SeoulNamsan-Bold.ttf
                weight: 700
              - asset: assets/fonts/SeoulNamsan-Medium.ttf
                weight: 600
              - asset: assets/fonts/SeoulNamsan-Regular.ttf
                weight: 500
              - asset: assets/fonts/SeoulNamsanL-Light.ttf
                weight: 400

        - family: Nunito
          fonts:
              - asset: assets/fonts/Nunito-Bold.ttf
                weight: 700
              - asset: assets/fonts/Nunito-Medium.ttf
                weight: 600
              - asset: assets/fonts/Nunito-Regular.ttf
                weight: 500
              - asset: assets/fonts/Nunito-Light.ttf
                weight: 400
